name: sdn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - setuptools=57.5.0
  - pip:
    # Core SDN Controller
    - ryu==4.34
    - eventlet==0.30.2
    - networkx==3.1
    
    # RYU Dependencies (Exact versions)
    - msgpack==1.1.1
    - oslo.config==9.6.0
    - oslo.i18n==6.4.0
    - Routes==2.5.1
    - WebOb==1.8.9
    - tinyrpc==1.1.7
    - ovs==3.5.1
    
    # Utilities
    - PyYAML==6.0.2
    - netaddr==1.3.0
    - pbr==6.1.1
    - six==1.17.0
    - dnspython==1.16.0
    - repoze.lru==0.7
    - stevedore==5.3.0
    
    # System Integration
    - greenlet==3.1.1
    - sortedcontainers==2.4.0
    
    # Optional
    - requests>=2.32.0
    - urllib3>=2.5.0
    - certifi>=2024.7.0
    - charset-normalizer>=3.4.0
    - idna>=3.10