name: sdn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - setuptools=57.5.0
  - pip:
    - ryu==4.34
    - eventlet==0.30.2
    - networkx>=3.1
    - msgpack>=1.0.0
    - oslo.config>=10.0.0
    - oslo.i18n>=6.5.0
    - ovs>=3.5.0
    - pbr>=6.1.0
    - Routes>=2.5.1
    - WebOb>=1.8.9
    - tinyrpc>=1.1.7
    - PyYAML>=6.0.0
    - netaddr>=1.3.0
    - six>=1.16.0
    - dnspython>=1.16.0
    - repoze.lru>=0.7
    - stevedore>=5.4.0
    - requests>=2.32.0
    - urllib3>=2.5.0
    - certifi>=2025.7.0
    - charset-normalizer>=3.4.0
    - idna>=3.10
    - greenlet>=3.2.0
    - sortedcontainers>=2.4.0